In [1]:
# PyTorchライブラリをインポートします。PyTorchは、深層学習に使用されるオープンソースの機械学習ライブラリです。
import torch

# torch.nnモジュールをnnとしてインポートします。このモジュールには、ニューラルネットワークの構築に必要なクラスや関数が含まれています。
# 例えば、畳み込み層(Conv2d)や全結合層(Linear)、活性化関数などが含まれます。
import torch.nn as nn

# torch.nn.functionalをFとしてインポートします。このモジュールには、ReLUやsoftmaxなどの活性化関数、
# また損失関数や畳み込みなどの関数的インターフェースが提供されています。
# 関数的インターフェースは、ステート（パラメータや学習可能な重み）を持たない層の操作に使用されます。
import torch.nn.functional as F

In [2]:
# scikit-learnライブラリからload_iris関数をインポートします。
# load_iris関数は、アイリスの花に関する有名なデータセットをロードするために使用されます。
# このデータセットは、アイリスの花の異なる3つの種類（セトサ、バーシカラー、バージニカ）について、
# 各サンプルに花びらの長さと幅、がく片の長さと幅の4つの特徴が含まれています。
from sklearn.datasets import load_iris

In [3]:
# load_iris関数を呼び出してアイリスデータセットをロードし、その結果をiris変数に格納します。
iris = load_iris()

In [4]:
#入力値と目標値を抽出
x = iris['data']
t = iris['target']

In [5]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
type(x), type(t)

(numpy.ndarray, numpy.ndarray)

In [7]:
# 既存のデータxをPyTorchのTensor型に変換します。データ型(dtype)をtorch.float32に指定しています。
# このデータ型は、一般的にニューラルネットワークの入力や内部計算で使用される32ビット浮動小数点数です。
x = torch.tensor(x, dtype=torch.float32)

# ラベルデータtをPyTorchのTensor型に変換します。データ型(dtype)をtorch.int64に指定しています。
# このデータ型は、一般的に整数値のラベルやインデックスとして使用される64ビット整数です。
t = torch.tensor(t, dtype=torch.int64)


In [8]:
type(x), type(t)

(torch.Tensor, torch.Tensor)

In [9]:
x.shape, t.shape

(torch.Size([150, 4]), torch.Size([150]))

# DataLoader

In [10]:
# 入力値xと目標値tをペアにしてTensorDatasetオブジェクトを作成します。
# TensorDatasetはPyTorchのデータセットクラスで、テンソルをラップしてイテレーターを通じてデータを提供する機能を持ちます。
# これにより、訓練データとターゲットラベルを一緒に管理しやすくなります。
dataset = torch.utils.data.TensorDataset(x, t)

In [11]:
len(dataset)

150

In [12]:
dataset[0]

(tensor([5.1000, 3.5000, 1.4000, 0.2000]), tensor(0))

# データセット分割

In [13]:
# 各データのサンプル数を決定
# train : val : test = 60% : 20% : 20%
n_train = int(len(dataset) * 0.6)
n_val = int(len(dataset) * 0.2)
n_test = len(dataset) - n_train - n_val

In [14]:
n_train, n_val, n_test

(90, 30, 30)

In [15]:
# PyTorchの乱数生成器にシード値0を設定します。
# この操作により、PyTorchを使用する際の乱数依存操作（例えば重みの初期化やデータのシャッフル）が
# 実行するたびに同じ結果を返すようになり、結果の再現性が保証されます。
torch.manual_seed(0)

In [16]:
# データセットの分割
train, val, test = torch.utils.data.random_split(dataset, [n_train, n_val, n_test])

In [17]:
len(train), len(val), len(test)

(90, 30, 30)

# ミニバッチ学習

訓練で用いるデータをいくつかのグループにデータを無作為に小分けして、グループごとの損失関数を計算して平均を算出し、学習を進めていきます。

In [18]:
# バッチサイズの定義
batch_size = 10

In [19]:
# トレーニングデータセット 'train' からデータローダーを作成します。
# 'batch_size' で指定されたサイズのバッチでデータをロードし、
# 'shuffle=True' によりエポックごとにデータをシャッフルし、
# 'drop_last=True' により最後の不完全なバッチをドロップします。これは、すべてのトレーニングバッチが同じサイズであることを保証します。
train_loader = torch.utils.data.DataLoader(train, batch_size, shuffle=True, drop_last=True)

# 検証データセット 'val' からデータローダーを作成します。
# ここではデータのシャッフルは行わず、エポックごとに同じ順番でデータが提供されます。
val_loader = torch.utils.data.DataLoader(val, batch_size)

# テストデータセット 'test' からデータローダーを作成します。
# 通常、テストデータでもシャッフルは行わず、予測時の再現性を確保します。
test_loader = torch.utils.data.DataLoader(test, batch_size)


In [20]:
# train_loaderデータローダーからイテレータを作成し、そのイテレータを使って次のデータバッチを取得します。
# この操作により、バッチサイズに基づいた特徴量のバッチ 'x' と目標値のバッチ 't' を取得できます。
# これは、モデルの訓練時に各ステップで使用されるデータバッチをロードする一般的な方法です。
x, t = next(iter(train_loader))

In [21]:
x

tensor([[7.7000, 3.8000, 6.7000, 2.2000],
        [5.0000, 3.4000, 1.6000, 0.4000],
        [5.5000, 3.5000, 1.3000, 0.2000],
        [6.4000, 2.8000, 5.6000, 2.2000],
        [6.7000, 2.5000, 5.8000, 1.8000],
        [7.7000, 3.0000, 6.1000, 2.3000],
        [5.1000, 2.5000, 3.0000, 1.1000],
        [5.0000, 3.6000, 1.4000, 0.2000],
        [7.3000, 2.9000, 6.3000, 1.8000],
        [6.1000, 2.8000, 4.0000, 1.3000]])

In [22]:
t

tensor([2, 0, 0, 2, 2, 2, 1, 0, 2, 1])

In [23]:
#ネットワークの定義

In [24]:
# 4⇨4⇨3の全結合層を定義

In [25]:
class Net(nn.Module):
  #使用するオブジェクト
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(4, 4)
    self.fc2 = nn.Linear(4, 3)

  #順伝播
  def forward(self, x):
    h = self.fc1(x)
    h = F.relu(h)
    h = self.fc2(h)
    return h

In [26]:
# PyTorchの乱数生成器のシードを0に設定します。この設定により、ネットワークの初期化やその他の乱数依存の操作が
# 実行される際に一貫した結果が得られるようになります。これは、結果の再現性を確保するのに役立ちます。
torch.manual_seed(0)

# 'Net' クラスのインスタンスを作成し、'net' 変数に格納します。
# このクラスはユーザーによって定義されたニューラルネットワークで、具体的な層や構成は 'Net' クラスの定義内で指定されます。
net = Net()


In [27]:
net

Net(
  (fc1): Linear(in_features=4, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=3, bias=True)
)

In [28]:
# 'net' ニューラルネットワークモデルのパラメータを更新するために、SGD（確率的勾配降下法）最適化器を使用します。
# 'lr=0.01' は学習率を意味し、この値によって各更新ステップでパラメータがどれだけ変更されるかが決まります。
# 学習率が高すぎると学習過程でパラメータが発散してしまい、低すぎると学習が進まなくなる可能性があります。
optimizer = torch.optim.SGD(net.parameters(), lr = 0.01)


In [29]:
batch = next(iter(train_loader))
batch

[tensor([[5.4000, 3.9000, 1.7000, 0.4000],
         [4.6000, 3.6000, 1.0000, 0.2000],
         [6.5000, 3.0000, 5.5000, 1.8000],
         [6.9000, 3.1000, 5.4000, 2.1000],
         [6.3000, 2.5000, 4.9000, 1.5000],
         [7.1000, 3.0000, 5.9000, 2.1000],
         [5.8000, 2.7000, 4.1000, 1.0000],
         [7.0000, 3.2000, 4.7000, 1.4000],
         [6.7000, 3.0000, 5.0000, 1.7000],
         [7.2000, 3.6000, 6.1000, 2.5000]]),
 tensor([0, 0, 2, 2, 1, 2, 1, 1, 1, 2])]

In [30]:
x, t = batch

In [31]:
x

tensor([[5.4000, 3.9000, 1.7000, 0.4000],
        [4.6000, 3.6000, 1.0000, 0.2000],
        [6.5000, 3.0000, 5.5000, 1.8000],
        [6.9000, 3.1000, 5.4000, 2.1000],
        [6.3000, 2.5000, 4.9000, 1.5000],
        [7.1000, 3.0000, 5.9000, 2.1000],
        [5.8000, 2.7000, 4.1000, 1.0000],
        [7.0000, 3.2000, 4.7000, 1.4000],
        [6.7000, 3.0000, 5.0000, 1.7000],
        [7.2000, 3.6000, 6.1000, 2.5000]])

In [32]:
t

tensor([0, 0, 2, 2, 1, 2, 1, 1, 1, 2])

In [33]:
# 予測値の算出
y = net.forward(x)
y

tensor([[-0.2557, -0.2605, -0.4679],
        [-0.2041, -0.2834, -0.5574],
        [-0.2786, -0.2244, -0.3632],
        [-0.2552, -0.2214, -0.3703],
        [-0.3241, -0.2302, -0.3493],
        [-0.2788, -0.2244, -0.3631],
        [-0.3241, -0.2302, -0.3493],
        [-0.3241, -0.2302, -0.3493],
        [-0.3090, -0.2282, -0.3539],
        [-0.1884, -0.2129, -0.3907]], grad_fn=<AddmmBackward0>)

In [34]:
# 'y' はモデルからの予測出力（通常はロジットまたは未スケーリングスコア）、't' は対応する正解ラベルです。
# F.cross_entropyは、これらの予測と実際のラベル間のクロスエントロピー損失を計算します。
# この損失関数は、モデルの予測が正解ラベルからどれだけ離れているかを数値化し、モデルの学習において
# パラメータの最適化の方向と大きさを導くために使用されます。
loss = F.cross_entropy(y, t)

In [35]:
loss

tensor(1.0882, grad_fn=<NllLossBackward0>)

In [36]:
# loss.backward() は損失関数の勾配を計算します。この計算は、モデルの各パラメータに対して行われ、
# 勾配はパラメータの .grad 属性に保存されます。この勾配は後続の最適化ステップ（例えば optimizer.step()）で
# 重みを更新する際に使用され、損失関数の最小化を目指します。このバックプロパゲーションは、
# ニューラルネットワークを効率的に訓練するための基本的なプロセスです。
loss.backward()

In [37]:
# 全結合層fc1の重みに関する勾配
print(f'fc1の重みの勾配:{net.fc1.weight.grad}')
print('-----')
#　全結合層fc1のバイアスに関する勾配
print(f'fc1のバイアスの勾配:{net.fc1.bias.grad}')
print('-----')
# 全結合層fc2の重みに関する勾配
print(f'fc2の重みの勾配:{net.fc2.weight.grad}')
print('-----')
#　全結合層fc2のバイアスに関する勾配
print(f'fc2のバイアスの勾配:{net.fc2.bias.grad}')
print('-----')

fc1の重みの勾配:tensor([[-0.2311, -0.1731, -0.0627, -0.0139],
        [ 0.7327,  0.3358,  0.6025,  0.2229],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])
-----
fc1のバイアスの勾配:tensor([-0.0461,  0.1060,  0.0000,  0.0000])
-----
fc2の重みの勾配:tensor([[-0.0652,  0.0259,  0.0000,  0.0000],
        [ 0.0366,  0.0227,  0.0000,  0.0000],
        [ 0.0285, -0.0486,  0.0000,  0.0000]])
-----
fc2のバイアスの勾配:tensor([ 0.1415, -0.0452, -0.0963])
-----


In [38]:
# optimizer.step() を呼び出して、モデルのパラメータを更新します。この関数は、
# loss.backward() で計算された勾配を使用して、パラメータを更新するための具体的なステップを実行します。
# このステップは最適化アルゴリズム（この例では SGD）によって定義されており、
# パラメータをより良い値へと調整し、最終的には損失を最小化することを目指します。
optimizer.step()


In [39]:
# 全結合層fc1の重みに関する勾配
print(f'fc1の重みの勾配:{net.fc1.weight}')
print('-----')
#　全結合層fc1のバイアスに関する勾配
print(f'fc1のバイアスの勾配:{net.fc1.bias}')
print('-----')
# 全結合層fc2の重みに関する勾配
print(f'fc2の重みの勾配:{net.fc2.weight}')
print('-----')
#　全結合層fc2のバイアスに関する勾配
print(f'fc2のバイアスの勾配:{net.fc2.bias}')
print('-----')

fc1の重みの勾配:Parameter containing:
tensor([[-0.0014,  0.2700, -0.4109, -0.3678],
        [-0.1999,  0.1307, -0.0159,  0.3942],
        [-0.0444,  0.1323, -0.1511, -0.0983],
        [-0.4777, -0.3311, -0.2061,  0.0185]], requires_grad=True)
-----
fc1のバイアスの勾配:Parameter containing:
tensor([ 0.1981,  0.2990, -0.3390, -0.2177], requires_grad=True)
-----
fc2の重みの勾配:Parameter containing:
tensor([[ 0.1823,  0.4149, -0.1029,  0.3742],
        [-0.0810,  0.0527,  0.4527, -0.4638],
        [-0.3151, -0.1261, -0.1949,  0.4320]], requires_grad=True)
-----
fc2のバイアスの勾配:Parameter containing:
tensor([-0.3255, -0.2297, -0.3484], requires_grad=True)
-----


In [40]:
#GPUを使うのが一般的
torch.cuda.is_available()

True

In [41]:
# torch.deviceを使用して計算の実行デバイスを指定します。
# 'cuda:0'は、利用可能な場合は最初のGPUを指し、torch.cuda.is_available()でGPUの可用性をチェックします。
# GPUが利用不可能な場合は、'cpu'を使用します。
# このデバイス指定により、モデルやデータを適切なデバイスに移動させて計算効率を最適化します。
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')


In [43]:
# ニューラルネットワークモデル 'net' を、先に設定した 'device' （GPUまたはCPU）に移動します。
# この操作により、モデルに関連する全ての計算が指定されたデバイス上で実行されるようになります。
# GPUが利用可能な場合、この操作は計算速度の向上に寄与し、大規模なモデルやデータセットの処理が効率的になります。
net.to(device)

Net(
  (fc1): Linear(in_features=4, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=3, bias=True)
)

In [46]:
# 入力データを、先に設定した 'device' （GPUまたはCPU）に移動します。
# この操作により、データとモデルが同じデバイス上にあるため、データ転送の遅延を避け、
# 計算効率を高めることができます。特に大量のデータを扱う場合や、高速な計算が求められる場合に重要です。
x = x.to(device)
t = t.to(device)

In [47]:
# 勾配情報の初期化
optimizer.zero_grad()

In [48]:
#　初期化後の勾配情報

# 全結合層fc1の重みに関する勾配
print(f'fc1の重みの勾配:{net.fc1.weight.grad}')
print('-----')
#　全結合層fc1のバイアスに関する勾配
print(f'fc1のバイアスの勾配:{net.fc1.bias.grad}')
print('-----')
# 全結合層fc2の重みに関する勾配
print(f'fc2の重みの勾配:{net.fc2.weight.grad}')
print('-----')
#　全結合層fc2のバイアスに関する勾配
print(f'fc2のバイアスの勾配:{net.fc2.bias.grad}')
print('-----')

fc1の重みの勾配:None
-----
fc1のバイアスの勾配:None
-----
fc2の重みの勾配:None
-----
fc2のバイアスの勾配:None
-----


In [54]:
# エポックの数
max_epoch = 10

In [55]:
torch.manual_seed(0)

In [56]:
# モデルのインスタンス化とデバイスへの転送
net = Net().to(device)

In [57]:
#最適化手法
optimizer = torch.optim.SGD(net.parameters(), lr=0.1)

In [58]:
# 学習のループ
for epoch in range(max_epoch):

  for batch in train_loader:
    x, t = batch
    x = x.to(device)
    t = t.to(device)

    y = net(x)

    loss = F.cross_entropy(y, t)

    print(f'loss:{loss}')

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

loss:1.0881630182266235
loss:1.0393922328948975
loss:1.002811312675476
loss:1.0250868797302246
loss:1.0088638067245483
loss:0.935197651386261
loss:0.8939587473869324
loss:0.9765416979789734
loss:0.9651519060134888
loss:0.8108386993408203
loss:1.0551203489303589
loss:0.9642282724380493
loss:0.9662469625473022
loss:0.932858943939209
loss:0.7749171853065491
loss:0.8114356994628906
loss:0.7223264575004578
loss:0.9744229316711426
loss:0.8967071771621704
loss:0.661658763885498
loss:0.7619714140892029
loss:0.7153902649879456
loss:0.6994240283966064
loss:0.8678095936775208
loss:0.9200590252876282
loss:0.7730971574783325
loss:0.8362565040588379
loss:0.6122376322746277
loss:0.7350387573242188
loss:0.674174964427948
loss:0.8070476651191711
loss:0.8895813822746277
loss:0.8203845024108887
loss:0.8040507435798645
loss:0.6486102938652039
loss:0.6044933199882507
loss:0.7059454321861267
loss:0.8517681360244751
loss:0.5676782727241516
loss:0.6980922818183899
loss:0.8395006060600281
loss:0.75976365804672

# 評価指標の追加

In [62]:
# トレーニングデータローダーから次のバッチを取得します。xは特徴量、tは対応するラベルです。
x, t = next(iter(train_loader))

# 特徴量のバッチ 'x' とラベルのバッチ 't' を、訓練に使用しているデバイス（GPUまたはCPU）に移動します。
# これにより、データとモデルが同じデバイス上で処理され、データ転送の遅延が最小化されます。
x = x.to(device)
t = t.to(device)

# モデル 'net' に特徴量 'x' を入力して予測 'y' を計算します。このとき、モデルはフォワードパスを実行し、
# 入力データに基づいた予測結果を出力します。
y = net(x)

# 'y' はモデルの予測結果を保持しています。この予測結果は次のステップで損失計算や評価に使用されます。
y


tensor([[ 1.9788, -1.2245, -2.3363],
        [-1.2275,  0.1243,  0.1997],
        [-1.2275,  0.1243,  0.1997],
        [ 2.5265, -1.4549, -2.7695],
        [ 2.3498, -1.3806, -2.6298],
        [-1.2275,  0.1243,  0.1997],
        [-1.2275,  0.1243,  0.1997],
        [-1.2275,  0.1243,  0.1997],
        [-1.1860,  0.1068,  0.1669],
        [ 2.1943, -1.3152, -2.5068]], device='cuda:0',
       grad_fn=<AddmmBackward0>)

In [63]:
# モデル出力 'y' の各行（各サンプルの予測）に対して最大値のインデックスを取得します。
# 'dim=1' は、行ごとの最大値を求めることを意味し、各サンプルに対する予測されたクラスラベルのインデックスを返します。
# これにより、モデルが各サンプルに対して最も可能性が高いと判断したクラスが得られます。
y_label = torch.argmax(y, dim=1)
y_label


tensor([0, 2, 2, 0, 0, 2, 2, 2, 2, 0], device='cuda:0')

In [65]:
# 'y_label'（予測されたクラスのインデックス）と 't'（実際のクラスのインデックス）を要素ごとに比較します。
# この比較により、モデルの各予測が正確かどうかを示すブール値のテンソルが生成されます。
y_label == t

tensor([ True,  True,  True,  True,  True,  True,  True, False, False,  True],
       device='cuda:0')

In [66]:
(y_label == t).sum()

tensor(8, device='cuda:0')

In [67]:
(y_label == t).sum().float()

tensor(8., device='cuda:0')

In [68]:
accuracy = (y_label == t).sum().float()/len(t)
accuracy

tensor(0.8000, device='cuda:0')

In [69]:
# モデルの初期化
torch.manual_seed(0)

# モデルのインスタンス化とデバイスへの転送
net = Net().to(device)

# 最適化手法の選択
optimizer = torch.optim.SGD(net.parameters(), lr=0.1)

In [70]:
# 学習のループ
for epoch in range(max_epoch):

  for batch in train_loader:
    x, t = batch
    x = x.to(device)
    t = t.to(device)

    y = net(x)

    loss = F.cross_entropy(y, t)

    #正解率追加
    y_label = torch.argmax(y, dim=1)
    accuracy = (y_label == t).sum().float()/len(t)
    print(f'accuracy: {accuracy:.2f}')

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

accuracy: 0.60
accuracy: 0.80
accuracy: 0.60
accuracy: 0.60
accuracy: 0.60
accuracy: 0.50
accuracy: 0.40
accuracy: 0.20
accuracy: 0.40
accuracy: 0.70
accuracy: 0.20
accuracy: 0.80
accuracy: 0.50
accuracy: 0.60
accuracy: 0.60
accuracy: 0.40
accuracy: 0.80
accuracy: 0.20
accuracy: 0.50
accuracy: 1.00
accuracy: 0.70
accuracy: 0.90
accuracy: 0.70
accuracy: 0.60
accuracy: 0.50
accuracy: 0.70
accuracy: 0.70
accuracy: 0.80
accuracy: 0.60
accuracy: 1.00
accuracy: 0.60
accuracy: 0.70
accuracy: 0.40
accuracy: 0.80
accuracy: 0.60
accuracy: 0.90
accuracy: 0.70
accuracy: 0.70
accuracy: 0.70
accuracy: 0.90
accuracy: 0.80
accuracy: 0.60
accuracy: 0.70
accuracy: 0.80
accuracy: 1.00
accuracy: 0.90
accuracy: 0.80
accuracy: 0.70
accuracy: 0.30
accuracy: 0.40
accuracy: 0.80
accuracy: 0.90
accuracy: 1.00
accuracy: 0.80
accuracy: 0.70
accuracy: 0.90
accuracy: 0.70
accuracy: 0.70
accuracy: 0.90
accuracy: 0.50
accuracy: 0.70
accuracy: 0.60
accuracy: 0.50
accuracy: 0.80
accuracy: 1.00
accuracy: 0.80
accuracy: 

In [71]:
# 正解率を計算する関数
def calc_accuracy(data_loader):

  with torch.no_grad():
    total = 0
    correct = 0.0

    for batch in data_loader:
      x, t = batch
      x = x.to(device)
      t = t.to(device)
      y = net(x)

      y_label = torch.argmax(y, dim=1)
      total += len(t)
      correct += (y_label == t).sum()

    #全体の平均を算出
    accuracy = correct / total

  return accuracy

In [72]:
calc_accuracy(val_loader)

tensor(0.7667, device='cuda:0')

In [73]:
calc_accuracy(test_loader)

tensor(0.6667, device='cuda:0')